#!/bin/bash
set -e -o pipefail -u

main() {
  if [[ $# -eq 0 ]]; then
    exec git submodule foreach --quiet \
      "\$toplevel/$(basename "$0") \$sm_path \$sha1 \$toplevel"
  fi

  local sm_path="$1"
  local sha1="$2"
  local toplevel="$3"

  local upstream # can't assume submodules have tracking branches
  for b in main master; do
    if git branch --remotes --list "origin/$b" | grep origin; then
      upstream="origin/$b"
      break
    fi
  done
  if [[ -z $upstream ]]; then
    echo >&2 "No main or master branch"
    exit 1
  fi

  local short_name; short_name="$(basename "$sm_path")"

  echo "Fetching $short_name"
  git fetch

  local count; count="$(git rev-list --count "$sha1..$upstream")"
  if [[ $count -eq 0 ]]; then
    exit 0
  fi

  local commit_msg
  printf \
    -v commit_msg \
    "Update %s (%d commits)\n\n%s\n" \
    "$short_name" \
    "$count" \
    "$(git_log)"

  git checkout --quiet "$upstream"

  cd "$toplevel"
  git add "$sm_path"
  git commit --message "$commit_msg"
}

git_log() {
  git --no-pager log \
    --abbrev-commit \
    --format=oneline \
    --graph \
    "$sha1..$upstream"
}

main "$@"
